import React from 'react'

export default function BattlingCagesWaiverContent() {
  return (
    <div className="flex-grow overflow-y-auto">
      <div className='text-sm mb-2 text-justify'>Each team and every participant in The Fun Roof "Batting Cages" must complete the WAIVER, RELEASE, and UNDERTAKING form. We hereby acknowledge and agree that participation in the Batting Cages located within The Fun Roof has inherent risks. In consideration of the services provided by The Fun Guys Corp with the trade name The Fun Roof, their staff, and all persons or entities acting in any capacity on their behalf (hereinafter referred to as The Fun Roof) we now agree and certify as follows:</div>
      <ul className="list-disc list-inside flex flex-col gap-4">
        <li className='text-sm text-justify'>I acknowledge and fully understand that the participant listed below will be engaging in activities that may involve a risk of serious injury which might result not only from my own actions, inactions, or negligence, but from the actions, inactions, or negligence of others or the conditions of the premises or of any equipment used. Further, there may be other risks not known or not reasonably foreseeable at this time. The risks may include, but are not limited to: the nature of the activity, latent or apparent defects or conditions in equipment or property supplied by The Fun Roof or other entities; acts of other participants in this activity, employees, or agents of The Fun Roof; my own physical condition, acts, or omissions; conditions of The Fun Roof facility and surrounding grounds or terrain and accidents connected with their use; first aid emergency treatment or other services.</li>
        <li className='text-sm text-justify'>I acknowledge that proper handling of the baseball bat is essential for safe participation in Batting Cages. I agree to use the baseball bat provided by The Fun Roof responsibly, with care, and exclusively for the said game. I will not use the baseball bat for any other activities.</li>
        <li className='text-sm text-justify'>I expressly agree and promise to accept and assume all the risks existing in this activity. My participation in this activity is purely voluntary, and I elect, in spite of the risks, to participate. I assume all the foregoing risks and accept personal responsibility for the damages following such injury.</li>
        <li className='text-sm text-justify'>On behalf of myself, I hereby voluntarily release, waive, forever discharge, and agree to indemnify and hold harmless The Fun Roof and each of their respective commissioners, directors, agents, and other employees, its parent, subsidiaries, affiliates, employees, distributors, and agents, other Batting Cages participants, and, if applicable, operators or lessors of premises used to conduct the event/activity, from any and all liability for any and all claims, demands, or causes of action which are in any way connected with my participation in this activity or my use of The Fun Roof equipment or facilities.</li>
        <li className='text-sm text-justify'>I acknowledge and certify that I am at least 18 years old, and I hereby undertake to immediately inform The Fun Roof personnel of any injuries, allergic reactions, or any instance requiring medical attention and provide The Fun Roof permission to administer basic First Aid, and I authorize The Fun Roof or its agents or employees to contact emergency personnel as needed.  I hereby understand that The Fun Roof shall neither be liable for any. I am responsible for any medical expenses incurred.</li>
        <li className='text-sm text-justify'>I hereby certify that I have read and am familiar with the Batting Cages Rules and Regulations and will comply with the conditions set forth therein.</li>
        <li className='text-sm text-justify'>I certify that I am in good health and physical condition to participate in Batting Cages. I acknowledge that it is my responsibility to assess my own physical limitations and seek medical advice if necessary.</li>
        <li className='text-sm text-justify'>I agree I will wear a helmet and closed-toe shoes at all times while in the Batting Cages. </li>
        <li className='text-sm text-justify'>The Fun Roof is not required to refund payments should there be power interruptions, late arrival of guests, or other instances that may cause the experience to be cut short or interrupted.</li>
      </ul>
    </div>
  )
}
