import React from 'react'

export default function CrazyGoldWaiverContent() {
  return (
    <div className="flex-grow overflow-y-auto">
      <div className='text-sm mb-2 text-justify'>Each team and every participant in The Fun Roof “Crazy Golf” must complete the Waiver of WAIVER, RELEASE, and UNDERTAKING form. We hereby acknowledge and agree that participation in The Throw located within The Fun Roof has inherent risks. In consideration of the services provided by The Fun Guys Corp. with the trade name The Fun Roof, their staff, and all persons or entities acting in any capacity on their behalf (hereinafter referred to as The Fun Roof) we now agree and certify as follows:</div>
      <ul className="list-disc list-inside flex flex-col gap-4">
        <li className='text-sm text-justify'>I acknowledge and fully understand that the participant listed below will be engaging in activities that may involve a risk of serious injury which might result not only from my own actions, inactions, or negligence, but from the actions, inactions, or negligence of others or the conditions of the premises or of any equipment used. Further, there may be other risks not known or not reasonably foreseeable at this time. The risks may include, but are not limited to: the nature of the activity, latent or apparent defects or conditions in equipment or property supplied by The Fun Roof or other entities; acts of other participants in this activity, employees, or agents of The Fun Roof; my own physical condition, acts, or omissions; conditions of The Fun Roof facility and surrounding grounds or terrain and accidents connected with their use; first aid emergency treatment or other services.</li>
        <li className='text-sm text-justify'>I acknowledge that proper handling of golf clubs is essential for safe participation in Crazy Golf. I agree to use the golf clubs provided by The Fun Roof responsibly, with care, and exclusively for the said game. I will not use the golf clubs for any other activities.</li>
        <li className='text-sm text-justify'>I expressly agree and promise to accept and assume all the risks existing in this activity. My participation in this activity is purely voluntary, and I elect, in spite of the risks, to participate. I assume all the foregoing risks and accept personal responsibility for the damages following such injury.</li>
        <li className='text-sm text-justify'>I hereby certify that I have read and am familiar with the Crazy Golf Rules and Regulations and will comply with the conditions set forth therein.</li>
        <li className='text-sm text-justify'>I certify that I am in good health and physical condition to participate in crazy golf. I acknowledge that it is my responsibility to assess my own physical limitations and seek medical advice if necessary.</li>
        <li className='text-sm text-justify'>I acknowledge and certify that I am at least 18 years old, and I hereby undertake to immediately inform The Fun Roof personnel of any injuries, allergic reactions, or any instance requiring medical attention and provide The Fun Roof permission to administer basic First Aid, and I authorize The Fun Roof or its agents or employees to contact emergency personnel as needed.  I hereby understand that The Fun Roof shall neither be liable for any. I am responsible for any medical expenses incurred.</li>
        <li className='text-sm text-justify'>I, on behalf of myself, my heirs, assigns, personal representatives, and next of kin, hereby release, discharge, indemnify, and hold harmless The Fun Roof, its owners, employees, agents, and affiliates, from any and all claims, liabilities, demands, actions, causes of action, costs, and expenses, whether at law or in equity, in connection with my participation in crazy golf at The Fun Roof. This release includes but is not limited to, claims for personal injury, property damage, or any other loss that may occur during or as a result of my participation.</li>
        <li className='text-sm text-justify'>I am aware that participating in activities involving Crazy Golf, the use or handling of any golf club, tools, or hardware at The Fun Roof, and related services or activities may involve risks, dangers, and hazards. Presence at the facility, even without direct engagement in the activities, could result in property damage, serious injury, or death. These risks may arise from the guest's own actions or failure to act safely, the negligent acts or omissions of The Fun Roof, or other clients, participants, or occupants of the facility.</li>
        <li className='text-sm text-justify'>The Fun Roof is not required to refund payments should there be power interruptions, late arrival of guests, or other instances that may cause the experience to be cut short or interrupted.</li>
      </ul>
    </div>
  )
}
