import React from 'react'

export default function GeneralWaiverContent() {
  return (
    <div className="flex-grow overflow-y-auto">
        <div className='text-sm mb-2 text-justify'>As you enjoy our exciting games at The Fun Roof, please keep in mind these safety reminders to ensure a safe and enjoyable adventure.  In consideration of the services provided by The Fun Guys Corp with the trade name The Fun Roof, their staff, and all persons or entities acting in any capacity on their behalf (hereinafter referred to as The Fun Roof) we now agree and certify as follows:</div>
        <ul className="list-disc list-inside flex flex-col gap-4">
            <li className='text-sm text-justify'>Guests must use and enjoy all attractions at The Fun Roof with care and diligence, avoiding any damage to the establishment. Any damage caused by guests due to misuse or mishandling of materials, objects, and furnishings inside the establishment may incur a minimum fine of P5,000.00.</li>
            <li className='text-sm text-justify'>Guests hereby undertake to be mindful at all times of their personal belongings and hereby release The Fun Roof from any loss or theft of personal belongings.</li>
            <li className='text-sm text-justify'>Guests hereby undertake to immediately inform The Fun Roof personnel of any injuries, allergic reactions, or any instance requiring medical attention. The Fun Roof shall provide first aid in case of injuries sustained inside its premises. However, Guests hereby understand that The Fun Roof shall neither be liable for any injuries sustained inside its premises nor shall it be compelled to reimburse medical expenses incurred due to injuries.</li>
            <li className='text-sm text-justify'>We kindly request guests to be aware that the food we serve may contain ingredients that include allergens such as eggs, sweeteners, flour, flavorings, peanuts, and others. For your safety, please exercise caution and inquire about allergen information before ordering. Kindly inform our staff of ANY allergies to these substances.</li>
            <li className='text-sm text-justify'>Prior to engaging in any activities on the premises, guests must provide information regarding any medical conditions that could affect their participation, including medical/mental conditions, pregnancy, or prior surgeries. Please note that this recreational facility may involve alcohol, and some of the games may be physically demanding. Guests are required to assume full responsibility for and acknowledge any potential risks that may arise during their time on the premises.</li>
            <li className='text-sm text-justify'>Guests understand that they may engage in activities involving a risk of serious injury, which may result from their own actions, inactions, or negligence, as well as the actions, inactions, or negligence of others or the condition of the premises or equipment used. There may also be unforeseen risks. These risks could include the nature of the activity, equipment or property issues, actions of other participants, employees, or agents, the guest's own physical condition, acts or omissions, facility conditions, terrain, and accidents connected with their use, as well as first aid or other services.</li>
            <li className='text-sm text-justify'>Guests acknowledge and adhere to the Rules & Regulations for the open-area games.</li>
            <li className='text-sm text-justify'>Guests are aware that participating in activities involving Shuriken throwing ("The Throw"), the use or handling of any shuriken, tools, or hardware at The Fun Roof, and related services or activities may involve risks, dangers, and hazards. Presence at the Facility, even without direct engagement in the activities, could result in property damage, serious injury, or death. These risks may arise from the guest's own actions or failure to act safely, the negligent acts or omissions of The Fun Roof, or other clients, participants, or occupants of the facility.</li>
            <li className='text-sm text-justify'>Guests acknowledge and certify that he/she is at least 18 years old. I hereby provide The Fun Roof permission to administer basic First Aid for minor injuries but is not liable for injuries requiring attention from healthcare professionals or any related financial obligations that may arise from said injuries. Guests authorize The Fun Roof or its employees to contact emergency personnel as needed and understand that he/she is responsible for any medical expenses incurred.</li>
            <li className='text-sm text-justify'>Guests hereby affirm my commitment to wearing safety gear (helmet) and closed-toe  shoes AT ALL TIMES while participating in games such as 'The Throw.'" and "The Batting Cages."</li>
            <li className='text-sm text-justify'>The Fun Roof is not required to refund payments should there be power interruptions, late arrival of guests, and other instances that may cause the experience to be cut short or interrupted;</li>
            <li className='text-sm text-justify'>The Fun Roof, its management, and employees are released from any liabilities of injuries, risks, and danger caused to the guests while inside the premises;</li>
            <li className='text-sm text-justify'>The Fun Roof, its management, and employees may prohibit individuals under the influence of medication or drugs from entering or participating on the premises.</li>
            <li className='text-sm text-justify'>Bringing of pets is strictly not allowed within the premises;</li>
            <li className='text-sm text-justify'>Bringing outside food and beverages while inside the premises is prohibited.</li>
        </ul>
    </div>
  )
}
